#include <linux/version.h>
#if LINUX_VERSION_CODE > KERNEL_VERSION(4,18,0)
#define snd_soc_write snd_soc_component_write
#define snd_soc_codec snd_soc_component
#define codec component
#define snd_soc_codec_get_drvdata snd_soc_component_get_drvdata
#define snd_soc_read snd_soc_component_read
#define snd_soc_update_bits snd_soc_component_update_bits
#define snd_soc_codec_driver snd_soc_component_driver
#define snd_soc_register_codec snd_soc_register_component
#define snd_soc_unregister_codec snd_soc_unregister_component
#define snd_soc_codec_get_bias_level snd_soc_component_get_bias_level
#define snd_soc_cache_sync snd_soc_component_cache_sync
#define snd_soc_codec_set_drvdata snd_soc_component_set_drvdata

#elif LINUX_VERSION_CODE < KERNEL_VERSION(4,15,0)
// #define snd_soc_component_write snd_soc_write
// #define snd_soc_component snd_soc_codec
#define component codec
#define snd_soc_component_get_drvdata snd_soc_codec_get_drvdata
// #define snd_soc_component_read snd_soc_read
// #define snd_soc_component_read32 snd_soc_read
#define snd_soc_component_update_bits snd_soc_update_bits
#define snd_soc_component_driver snd_soc_codec_driver
#define snd_soc_register_component snd_soc_register_codec
#define snd_soc_unregister_component snd_soc_unregister_codec
#define snd_soc_component_get_bias_level snd_soc_codec_get_bias_level
#define snd_soc_component_cache_sync snd_soc_cache_sync
#define snd_soc_component_set_drvdata snd_soc_codec_set_drvdata


#endif
